name: 'New image to /r/imagegonord'

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 12 * * 3,6'
jobs:
  upload_and_convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload and convert image to IGN
        uses: ./reddit-posts-automation
        env:
          REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
          REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
          REDDIT_APP_ID: ${{ secrets.REDDIT_APP_ID }}
          REDDIT_APP_SECRET: ${{ secrets.REDDIT_APP_SECRET }}
          SUBREDDIT: ${{ secrets.SUBREDDIT }}