name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for contributing to the project! We will reply as soon as possible to your problem or request :)'
        pr-message: 'Thanks for contributing to the project! We will revise the code as soon as possible :)'
